# frozen_string_literal: true

source 'https://rubygems.org'

group :development, :test do
  gem 'rake'
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'simplecov', require: false
end
