# frozen_string_literal: true

require 'rspec/core/rake_task'
namespace :test do
  desc 'Run unit tests'
  RSpec::Core::RakeTask.new(:unit) do |t|
    t.pattern = 'spec/unit/**{,/*/**}/*_spec.rb'
  end

  desc 'Run integration tests'
  RSpec::Core::RakeTask.new(:integration) do |t|
    t.pattern = 'spec/integration/**{,/*/**}/*_spec.rb'
    t.rspec_opts = '--fail-fast'
  end
end

task default: 'test:unit'
